### ISSUE TITLE
Apps eventually fail with "You need to use a Theme.AppCompat theme (or descendant) with this activity"

### ISSUE THREAD

**Issue by ericbn** [SpiritCroc/DefaultDarkTheme-cmte#1]
This was `com.android.email` after clicking on one of its notifications:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.email/com.android.email2.ui.MailActivityEmail}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:310)
	at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:279)
	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:253)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
	at com.android.mail.ui.MailActivity.onCreate(MailActivity.java:176)
	at com.android.email2.ui.MailActivityEmail.onCreate(MailActivityEmail.java:82)
	at android.app.Activity.performCreate(Activity.java:6251)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
	... 9 more
```

Also happens when opening app directly on its icon. Opening the app again after it crashes with the error above usually works.

**Comment by SpiritCroc** [comment]
Thank you for providing a log, that helps a lot.
I never experienced this issue and are currently using a ROM without 
CMTE, so I can't test it at the moment.
I'll publish an updated to the beta channel soon (enable beta updates 
here: 
https://play.google.com/apps/testing/de.spiritcroc.defaultdarktheme_cmte), 
could you please test and report back?

**Comment by ericbn** [comment]
Sure, let me know when beta is updated. I'm using CyanogenMod 13.0-20160820-SNAPSHOT-ZNH5YAO0J5-mako.

**Comment by SpiritCroc** [comment]
Just uploaded, should be available within one hour

**Comment by ericbn** [comment]
Steps:
1. Updated Default Dark CM13 Theme, 
2. applied the System theme and then 
3. applied the DefaultDarkTheme back. 

On first run, email failed with:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.email/com.android.email2.ui.MailActivityEmail}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4111)
	at android.app.ActivityThread.-wrap15(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:310)
	at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:279)
	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:253)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
	at com.android.mail.ui.MailActivity.onCreate(MailActivity.java:176)
	at com.android.email2.ui.MailActivityEmail.onCreate(MailActivityEmail.java:82)
	at android.app.Activity.performCreate(Activity.java:6251)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
	... 10 more
```

The `com.android.messaging` also failed with the same error, but I could not capture the stack trace (sorry, my fault).

Tried repeating the steps above, but no errors happened.  :- /

**Comment by ericbn** [comment]
Update: I'm still randomly getting the error for email after installing the beta. Already happened more than a couple of times.

**Comment by SpiritCroc** [comment]
Thanks for reporting, will look into this again when I find time

**Comment by SpiritCroc** [comment]
So, just wanted to post an update.
I didn't find time to look into this further. As I'm currently on Nougat and nobody knows when (or even if?) CMTE will come back, it's not a priority for me at the moment.
I'm sorry to tell you that I probably won't fix this issue soon, even though the logcat gives some good clues about what is going on.
Thanks for reporting either way, maybe I'll find a fix while working on the OMS variant (or when CMTE is back); but that's all for now, sorry!

**Comment by ericbn** [comment]
@SpiritCroc, fair enough. And thanks for the heads up!
